### ISSUE TITLE
Copy block and add page link to block

### ISSUE THREAD

**Issue by coolwyz** [vipzhicheng/logseq-plugin-copy-ref-to-journal#10]
I do not use ref block，Each weekend I copy the next week's TODO and link that page to the following week's diary
like this
![image](https://user-images.githubusercontent.com/32034233/189518168-b120dfd4-e1ac-432b-807d-1785c726d307.png)
Do you think it is possible to create a similar function

**Comment by vipzhicheng** [comment]
I can not get your idea. Seems a function like the plugin `Block to page`.

**Comment by vipzhicheng** [comment]
Did you notice when you press `cmd+shift+m`, you can trigger a modal, there are many options there, you can have a try to see if it fits your needs.

<img width="792" alt="Snipaste_2022-10-24_17-28-12" src="https://user-images.githubusercontent.com/1209538/197495025-7ad43a28-9d64-473a-9080-6930afdb3bd5.png">
