### ISSUE TITLE
Keyboard shortcut conflicts with Markmap plugin

### ISSUE THREAD

**Issue by almereyda** [vipzhicheng/logseq-plugin-copy-ref-to-journal#11]
When starting LogSeq, an error is thrown that reads:

> :plugin.logseq-mark-map/mark-map-open-full ctrl+shift+m ctrl+shift+m Keyboard shortcut conflicts with existing shortcut: plugin.logseq-copy-ref-to-journal/move-block

I don't know which one should be given precedence here, or how to configure the plugin.

---

This is the mirror version of

- https://github.com/vipzhicheng/logseq-plugin-mark-map/issues/47

**Comment by flatrick** [comment]
@almereyda you can change the keybinding by editing the following file (Windows):  
`%userprofile%\.logseq\settings\logseq-move-block.json`

Or if you're a powershell-user:
`$env:userprofile\.logseq\settings\logseq-move-block.json`

But yeah, both this plugin and `logseq-plugin-mark-map` ought to make it more intuitive to change the setting inside of Logseq
