### ISSUE TITLE
Use Logseq locale settings for calendar

### ISSUE THREAD

**Issue by stdword** [vipzhicheng/logseq-plugin-copy-ref-to-journal#15]
### Plugin display wrong first day of week:
<img width="300px" src="https://user-images.githubusercontent.com/1984175/232828298-8d892d4f-b938-4577-8fa8-3859b6c39e2a.png"/>

### Logseq `config.edn`:
<img width="500px" src="https://user-images.githubusercontent.com/1984175/232827789-c69dfbc9-069d-454f-bdd0-ae6e0ffddcd0.png"/>

**Comment by vipzhicheng** [comment]
This idea is finally implemented in the latest version. Please have a look.

**Comment by stdword** [comment]
Thank you! It is working! 🙏
