### ISSUE TITLE
Feature Request: Move to target block

### ISSUE THREAD

**Issue by jjaychen1e** [vipzhicheng/logseq-plugin-copy-ref-to-journal#18]
Nice plugin! But it is nice if it can support to move blocks to a direct block by specifying the uuid of the target block.

**Comment by vipzhicheng** [comment]
It's implemented in the latest version. But I also made the plugin as a paid plugin and the target block feature is in the Pro plan. To thank you for the idea, I can send you a license. Please leave your email here or DM me your email on Twitter.
