### ISSUE TITLE
Move to other LogSeq Graph

### ISSUE THREAD

**Issue by rjdverbeek-tud** [vipzhicheng/logseq-plugin-copy-ref-to-journal#21]
Would it be possible to move a block that is part of a Journal Page to a Journal Page in another LogSeq Graph?

This would help moving blocks between Graphs.

For ease of use it would be great if it would to the journal page with the same date.

**Comment by vipzhicheng** [comment]
It's impossible because all move actions depend on Logseq API, which is designed to be used in one Graph but not cross graphs.
