### ISSUE TITLE
Moving to Journal, respecting active template 

### ISSUE THREAD

**Issue by kohennigs** [vipzhicheng/logseq-plugin-copy-ref-to-journal#22]
Good Morning! 

Gerat Plugin! It saves me a lot of time! 

Would in be possible to respect
 :default-templates
while moving a block to tomorrow e.g. (if the journal page did not exist)? 

Thanks!

**Comment by vipzhicheng** [comment]
I dug this for a while and found that it's impossible for now. there is no API to set multi-lines content to a page as multi-lines blocks

**Comment by kohennigs** [comment]
Ok, thanks for the feedback. 

Kind regards. 

Kai
