### ISSUE TITLE
Move Block Pro License

### ISSUE THREAD

**Issue by cullen-dev** [vipzhicheng/logseq-plugin-copy-ref-to-journal#24]
Hey @vipzhicheng,

I am reaching out because I purchased a Move Block "Pro" license yesterday and have not received the license Key. Twitter won't let me DM you, so I tweeted at you [yesterday](2024-07-14)  in an attempt to contact you. My twitter handle is @indicul. Not sure if you have seen that yet or not, but I wanted to reach out another way just in case!

I would like to start using the Move Block "Pro" features as soon as possible. I am happy to provide any proof/verification of purchase that you need. I have the confirmation email and will attach a screenshot of that to this issue.

Thanks so much for your contributions to Logseq. I already love the free version of Move Block! I totally understand that you are busy, so no worries about the delay. Just please reach out to me as soon as you see this message!

Have a great day,
Cullen
Twitter: @indicul
Email: cullenb829@gmail.comhttps://docs.github.com/articles/github-community-guidelines
GitHub: cullen-vlsci

Screenshot, Buy Me a Coffee
<img width="958" alt="qD5lIwT7vl" src="https://github.com/user-attachments/assets/12a3dcfc-1784-4098-9eb0-81a71691ec25">

Screenshot, Move Block License - Confirmation Email
![move_block_license_confirmation_email](https://github.com/user-attachments/assets/96d4efc7-c61e-433f-b891-b996398eb175)

**Comment by vipzhicheng** [comment]
Sorry for the delay! The license-sending job is done manually. I have sent you the license just now, please check your email.

BTW. I often check the order list per day.

**Comment by cullen-dev** [comment]
No worries at all!! I totally understand. I have just been eager to get my hands on it. I appreciate your quick response!
