### ISSUE TITLE
Feature request: Remove right click context menu option "copy block ref to contents"

### ISSUE THREAD

**Issue by drawingthesun** [vipzhicheng/logseq-plugin-copy-ref-to-journal#3]
Hi,

Would it be possible to expose an option in settings to so I can set this plugin to turn off the option in the right click menu "copy block ref to contents".

Whilst I make heavy use of the Contents page, I never copy block ref's there.

Since I used your plugin before the update I make a huge amount of use from the option "copy block ref to journal" - that is so useful! But the contents option - I will never use.

Thanks for this plugin it has helped a lot!

**Comment by vipzhicheng** [comment]
That makes sense, I will wipe it out in next release.

**Comment by vipzhicheng** [comment]
Done, please update.
