### ISSUE TITLE
Block moves to the day before the journal date I select

### ISSUE THREAD

**Issue by dwrhodes** [vipzhicheng/logseq-plugin-copy-ref-to-journal#4]
Love the new options. This really improves my workflow. The only issue I've noticed is that if I select:

To: A journal
Select a date

The block gets moved to the day before I select.

Moving to today's journal seems to work correctly.

Not sure if this could be a time-zone issue. Probably not, since all activity is local.

**Comment by vipzhicheng** [comment]
What is your preferred date format?

**Comment by dwrhodes** [comment]
yyyy-MM-dd EEE

**Comment by vipzhicheng** [comment]
@dwrhodes Please upgrade, I just released a new version to try to fix it.

**Comment by dwrhodes** [comment]
@vipzhicheng I tried it several times and got the same result with the new version. It always goes to the day before I select.

By the way, I really like the new Bottom/Top option.

**Comment by vipzhicheng** [comment]
What is your time zone? Seem I need to do more test

**Comment by dwrhodes** [comment]
America/Los_Angeles

**Comment by vipzhicheng** [comment]
A new version was released. Please help to confirm!

**Comment by dwrhodes** [comment]
It seems to work now. I was able to move items between several journal pages, and it always hit the right date. Thanks!
