### ISSUE TITLE
Feature Request: more specific movement: block to > A block

### ISSUE THREAD

**Issue by cesar-programs** [vipzhicheng/logseq-plugin-copy-ref-to-journal#6]
scenario: we have a block that we want to move under another specific block

currently, we can move blocks to a page, and either the bottom or top; however, we may know exactly where we want the block to be placed. ideally, we could search for a specific block and move the contents of the block we are working on under that block. 

thank you

**Comment by vipzhicheng** [comment]
I got your idea, but do not have a good design about the UI interaction. Block level search may be hard to decide which one is which one. like one page has many same content blocks.

And about the operation steps, I think it needs more steps to operate, maybe it's better to just copy or cut and then go to that page to put under the target block.

**Comment by cesar-programs** [comment]
Thanks for the reply :)
