### ISSUE TITLE
Move to Journal - tomorrow

### ISSUE THREAD

**Issue by StanBright** [vipzhicheng/logseq-plugin-copy-ref-to-journal#7]
Hey, thanks for the awesome plugin. 

It's quite convenient, and it optimizes my work every day. 

**I'm wondering, how difficult would it be to implement an option to move a selected block to "tomorrow"?** 

Quite often, I find myself moving some of my tasks to tomorrow. As of now, I have to go and pick the day manually every day. I have a feeling that it should be relatively easy to add an option of "tomorrow".

Thanks!

**Comment by vipzhicheng** [comment]
It's in it now. Please take look.
