### ISSUE TITLE
replace block embed?

### ISSUE THREAD

**Issue by notuntoward** [vipzhicheng/logseq-plugin-copy-ref-to-journal#8]
With the `copy block embed` option, I can write a block on my journal page and then easily embed it in some new page.  This is really nice, but I've found that I'd really like to do is the same, but opposite.  In other words, I'd like to put the cursor on a journal page block, then run `replace block embed`, which would:

1. copy the block to a new page
2. replace the original journal page block with an embed to that block on the new page

One use case is a book reading note, where I'd like to keep all the notes a book's page, but would also like to see what I did on each day in the journal.   Other use cases are entries I write in my journal which, over time, I realize belong to a single topic.  I'd like to move these entries to a single new page, yet keep the record in my journal.

**Comment by vipzhicheng** [comment]
I have added a new action "Cut content and keep embed to target". Seems it can solve your situation. Please take a look.

**Comment by notuntoward** [comment]
Thanks for the improvement!
